[versions]
agp = "8.3.0"
kotlin = "1.9.20"
compose = "2023.10.01"
securityCrypto = "1.1.0-alpha06"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
